config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :items do 
    resources :comments, only: [:create]
  end

  # users
  get "/login", to: "users#login"
  post "/login", to: "users#sign_in"
  delete "/logout", to: "users#logout"
  get "/sign_up", to: "users#sign_up"
  post "/sign_up", to: "users#registration"

  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def add_item(item_id)
    found_item = items.find { |item| item.item_id == item_id }

    if found_item
      found_item.increment!   # 增加數量
    else
      items << CartItem.new(item_id)
    end
  end

  def empty?
    items.empty?
  end

  def total
    result = items.sum { |item| item.total }

    # 4/1 全館打 1 折
    if Time.now.month == 4 and Time.now.day == 1
      result = result * 0.1
    end

    return result
  end

  def self.from_hash(hash = nil)
    if hash && hash["items"]
      items = hash["items"].map { |item|
        CartItem.new(item["item_id"], item["quantity"])
      }

      new(items)
    else
      new
    end
  end

  def to_hash
    items = @items.map { |item|  
      { "item_id" => item.item_id, "quantity" => item.quantity } 
    }

    return { "items" => items }
  end
end

app/models/cart_item.rb
class CartItem
  attr_reader :item_id, :quantity

  def initialize(item_id, quantity = 1)
    @item_id = item_id
    @quantity = quantity
  end

  def increment!(amount = 1)
    @quantity += amount
  end

  def item
    Item.find(item_id)
  end

  def total
    item.price * quantity
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :content, presence: true, length: { minimum: 2 }
  default_scope { order(id: :desc).where(deleted_at: nil)}
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :histories
  has_many :users, through: :histories
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, 
                    numericality: { greater_than: 0 }

  has_many :comments
  belongs_to :category

  has_one_attached :cover

  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.now)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, 
                       confirmation: true, 
                       length: { minimum: 4 }

  has_many :histories
  has_many :events, through: :histories
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, 
              with: :record_not_found

  before_action :check_login

  helper_method :current_user

  private
  def check_login
    redirect_to login_path unless current_user
  end

  def record_not_found
    render file: 'public/404.html', 
           status: 404, 
           layout: false
  end

  def current_user
    User.find_by(id: session[:ccc9527])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])

    @comment = @item.comments.build(comment_params.merge(user: current_user))
    
    if @comment.save
      # render json: {name:"herry" , age: 19}  JSON 畫面輸入值後 不會跳轉 但重整後資料會新增
      # redirect_to item_path(params[:item_id]), notice: 'ok'
    else
      render 'items/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy] 

  def index
    @items = Item.all
  end

  def show
    @comment = Comment.new
    
    # eager loading
    @comments = @item.comments.includes(:user) 
                              #  order(id: :desc)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path, notice: '成功新增餐點!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to items_path, notice: '成功更新餐點!'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, notice: '成功刪除餐點'
  end

  private
  def find_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, 
                                 :description, 
                                 :price, 
                                 :category_id,
                                 :cover,
                                 :spec)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :check_login

  def login
    @user = User.new
  end

  def sign_up
    @user = User.new
  end

  def sign_in
    user = User.find_by(email: user_params[:email], 
                        password: user_params[:password])

    if user 
      session[:ccc9527] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def registration
    @user = User.new(user_params)
    if @user.save
      session[:ccc9527] = @user.email
      # TODO: 密碼加密
      redirect_to root_path
    else
      # 失敗
      render :sign_up
    end
  end

  def logout
    session[:ccc9527] = nil
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:email, 
                                 :password, 
                                 :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>

  <% if category.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>分類</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
 <div class="alert alert-dark" role="alert">
    <p><%= comment.content %></p>
    <hr>
    <p class = "mb-0">postedBy<%= comment.user.email %> / <%= comment.created_at %></p>
  </div>

app/views/comments/create.js.erb
var comments = document.querySelector('#comments');
comments.innerHTML = "<%= j render('comments/comment', comment: @comment) %>" + comments.innerHTML;

document.querySelector('#comment_content').value = ""

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>

  <% if item.errors.any? %>
    <ul>
    <% item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :cover %>
    <%= f.file_field :cover %>
  </div>

  <div>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true %>
  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div>
    <%= f.label :spec %>
    <%= f.text_field :spec %>
  </div>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>編輯餐點</h1>

<%= render 'form', item: @item %>

app/views/items/index.html.erb
<h1>餐點列表</h1>

<%= link_to "新增", new_item_path %>

<div class="row">
  <% @items.each do |item| %>
    <div class="col-4 item">
      <div class="card">
        <%= image_tag item.cover.variant(resize_to_limit: [200, 200]), class: 'cover-image' if item.cover.attached? %>
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to item.name, item %>
          </h5>
          <%= link_to "編輯", edit_item_path(item), class: 'btn btn-primary' %>
          <%= link_to "刪除", item, method: 'delete', data: {confirm: "是否確認刪除?"}, class: 'btn btn-success' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<h1>新增餐點</h1>

<%= render 'form', item: @item %>

app/views/items/show.html.erb
 <%# item_controller.js    h1內 %>
<h1 data-controller = "item">
<%= @item.name %> 
                                                <%# item_controller.js的heart功能 %>
<a href = "#" class= "btn btn-danger" data-action = "item#heart">
                        <%# item_controller.js的圖標 static targets = ["icon"] %>
<i class="far fa-heart" data-target = "item.icon"></i></a>
</h1>

<ul>
  <li>價錢：<%= @item.price %> </li>
</ul>

<div data-controller = "comment">

<h3>留言</h3>
<%= form_for(@comment, url: item_comments_path(@item),remote: true ) do |form| %>
  <div class = "form-group"> 
    <%= form.text_area :content , class: "form-control" ,data: {target: 'comment.content' , 
                                                        action: 'keyup->comment#check'} %>
  </div>
<%= form.submit '我要評價', class: 'btn btn-info', disabled: true, data: { target: 'comment.submit' } %>
 <%# 反灰 %>
  <% end %>
</div>
<hr>
<div id = "comments">
  <% @comments.each do |comment| %>
  <%= render 'comments/comment' , comment: comment %>
<% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinbendon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flash" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
2020 &copy; 吃飯

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">訂便當</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "餐點列表", items_path, class: 'nav-link' %>
      </li>

      <% if current_user %>
        <li class="nav-item">
          <%= link_to "我要開團", "#", class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <a href="/sign_up" class="nav-link">註冊</a>
        </li>
        <li class="nav-item">
          <a href="/login" class="nav-link">登入</a>
        </li>
      <% end %>
    </ul>

    <% if current_user %>
      日安，<%= current_user.email %>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "登出", logout_path, method: 'delete', class: 'nav-link' %>
      </li>
    </ul>
    <% end %>
  </div>
</nav>

app/views/users/login.html.erb
<h1>使用者登入</h1>

<%= form_for(@user, url: login_path, method: 'post') do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password, "密碼" %>
    <%= f.password_field :password %>
  </div>

  <%= f.submit "登入" %>
<% end %>

app/views/users/sign_up.html.erb
<h1>使用者註冊</h1>

<%= form_for(@user, url: '/sign_up', method: 'post') do |f| %>

  <% if @user.errors.any? %>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password, "密碼" %>
    <%= f.password_field :password %>
  </div>
  
  <div>
    <%= f.label :password_confirmation, "確認密碼" %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit "註冊" %>
<% end %>

app/views/welcome/index.html.erb
<h1>你好</h1>